### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by lalbri** [MorpheusXAUT/DelHel#12]
Initial climb altitude are currently per SID. I would suggest shift it on rwy base.

**Comment by cleptric** [comment]
This wouldn't work, as some airports have different initial climbs based on the SID from the same RWY.

**Comment by lalbri** [comment]
Is it possible  to turn off annoyng blinking "DelHel" chat folder to every variation of SID?

**Comment by MorpheusXAUT** [comment]
What exactly are you talking about? The messages being sent by DelHel on certain validation errors/hints? Any specific message that keeps popping up for you?
There's an issue with one part of the route validation that leads to excess `Some Waypoints may be incorrect. Check routing!` messages, which will be fixed in the next release. Are those the ones you're talking about?

**Comment by lalbri** [comment]
Negative.
Attached two screenshots can be more explicative.
Word DelHel on the screenshot blinks at one and every message of DelHel action.  
If this is manageable via programming, I suggest you to exclude blinking and let it only highlighted.
![Screenshot_3](https://user-images.githubusercontent.com/49708851/119966505-a8f6ee00-bfab-11eb-9737-fbcd001fc813.png)
![Screenshot_4](https://user-images.githubusercontent.com/49708851/119966536-b14f2900-bfab-11eb-9205-fdb383b39a7d.png)

**Comment by MorpheusXAUT** [comment]
For now, you can disable debug mode (which is why DelHel logs the information you showed) by running `.delhel debug`.
I can look into adding an option for disabling the blinking in the next release (it's just show a solid colour on every message instead, but should not blink).

**Comment by MorpheusXAUT** [comment]
@lalbri The latest version (https://github.com/MorpheusXAUT/DelHel/releases/tag/v0.0.6) has a command to disable the flashing: `.delhel flash`
Unfortunately, it seems like changing the setting does not apply immediately, you'll have to disable flashing, then save your plugin settings and restart EuroScope for it to apply properly.

**Comment by lalbri** [comment]
> Initial climb altitude are currently per SID. I would suggest shift it on rwy base of same SID
i.e.:

![image](https://user-images.githubusercontent.com/49708851/187072095-9cc2f27f-6eef-4cfa-9bfe-f482e30827a4.png)

**Comment by lalbri** [comment]
Better adding "comventional" departure to "dep" and "nap":
![image](https://user-images.githubusercontent.com/49708851/187074805-241e7937-ec0a-4b84-8eef-299e71fbe9c7.png)
