### ISSUE TITLE
Altitude constrant attached to SDI FIX

### ISSUE THREAD

**Issue by lalbri** [MorpheusXAUT/DelHel#14]
Sometimes FLPs include altitude constraint attached to SID FIX.
DelHel doesn't recognize the SID FIX if it includes altitude constraint ( ANYFIX/N0447F350+ ). 
It would be fine if DelHel could extract a clain SID FIX if a slash  is encountered in it, before processing.

**Comment by MorpheusXAUT** [comment]
Added, will be included in the next release.

**Comment by MorpheusXAUT** [comment]
Hi @lalbri,

sorry for the delay, this has been fixed in [v0.0.7](https://github.com/MorpheusXAUT/DelHel/releases/tag/v0.0.7).
