### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by Iwhite67** [MorpheusXAUT/DelHel#5]
Hello

I search to know how edit rounting.json

Example
BADOD SID need to have RFL up to 195 
and 
RUBIT Below 115 and is a sid only for LFTH

**Comment by FreshDave29** [comment]
Hello,
please elaborate on the type of bug and how to recreate it.

in the routing.json you enter the departure icao as root element, and the SID-exitpoints as "name". Within the "route"-element you can specify the destination icao and the corresponding min/max altitudes in FL (=feet/100).
If no icao is present, all routes using this SID are restricted.
Waypoints after the SID-exitpoint are optional.

Best,
David

**Comment by Iwhite67** [comment]
Thanks you for this info, i will go check

**Comment by FreshDave29** [comment]
in addition, after changing the .json, use this validator to check whether all inputs and parenthesis are corret.

https://jsonformatter.curiousconcept.com/

**Comment by Iwhite67** [comment]
"in the routing.json you enter the departure icao as root element"

I set LFMM is for all aircraft overflight LFMM
LFMN is only for Aircraft departing from LFMN

is right ?

**Comment by FreshDave29** [comment]
Documentation updated with 0.0.3
